services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - "25565:25565"
    environment:
      # General Options
      USE_AIKAR_FLAGS: true
      MEMORY: 8G
      # Server
      EULA: true
      VERSION: 1.18.2
      ALLOW_FLIGHT: true
      # CurseForge
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY} # allocate from https://console.curseforge.com/
      CF_FORCE_SYNCHRONIZE: true
      CF_SLUG: dawn-craft
      CF_EXCLUDE_MODS: compass-coords
    volumes:
      - data:/data

volumes:
  data: {}